# Generated by Django 6.0.5 on 2026-08-20 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 8, 19, 17, 31, 9, 948323)),
        ),
    ]
