# Generated by Django 6.1 on 2026-09-10 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_order_date_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 9, 10, 23, 6, 17, 884413)),
        ),
    ]
