# Generated by Django 6.1 on 2026-09-12 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 9, 12, 21, 52, 44, 651617)),
        ),
    ]
