# Generated by Django 6.1 on 2026-09-19 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 9, 19, 16, 21, 13, 22469)),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
