# Generated by Django 6.1 on 2026-09-19 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_order_date_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 9, 19, 17, 49, 52, 266574)),
        ),
    ]
