# Generated by Django 6.0.5 on 2026-08-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'waiting to pay'), ('processing', 'waiting to process'), ('shipped', 'sending to post'), ('delivered', 'is delivered')], default='pending', max_length=50),
        ),
    ]
