# Generated by Django 6.0.5 on 2026-07-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingdress',
            options={'verbose_name_plural': 'shippingdress'},
        ),
        migrations.RenameField(
            model_name='shippingdress',
            old_name='address1',
            new_name='shipping_address1',
        ),
        migrations.RenameField(
            model_name='shippingdress',
            old_name='city',
            new_name='shipping_city',
        ),
        migrations.RenameField(
            model_name='shippingdress',
            old_name='countary',
            new_name='shipping_countary',
        ),
        migrations.RenameField(
            model_name='shippingdress',
            old_name='emails',
            new_name='shipping_email',
        ),
        migrations.RenameField(
            model_name='shippingdress',
            old_name='full_name',
            new_name='shipping_full_name',
        ),
        migrations.RenameField(
            model_name='shippingdress',
            old_name='phone',
            new_name='shipping_phone',
        ),
        migrations.RenameField(
            model_name='shippingdress',
            old_name='state',
            new_name='shipping_state',
        ),
        migrations.RenameField(
            model_name='shippingdress',
            old_name='zipcode',
            new_name='shipping_zipcode',
        ),
        migrations.RemoveField(
            model_name='shippingdress',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='shippingdress',
            name='old_cart',
        ),
        migrations.AddField(
            model_name='shippingdress',
            name='shipping_address2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
