# Generated by Django 6.0.5 on 2026-08-20 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='products',
            new_name='product',
        ),
    ]
